name: ZEngine Linux Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  PROJECT_ROOT_DIR: .
  OUTPUT_BUILD_DIR: .\out\build

jobs:
  Linux-Build:
    runs-on: ubuntu-18.04	
    strategy:
      matrix:
          buildSystem: [Linux]
          buildPlatform: [x64]
          buildConfiguration: [Release]

    steps:      
    - name: check out repository
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
    
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 7
        platform: x64

    - name: Define Clang 7 as default compiler
      run: export CC=/usr/bin/clang-7
      run: export CXX=/usr/bin/clang++-7

    - name: Check CMake Version
      run: cmake --version
      
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{env.PROJECT_ROOT_DIR}} -B ${{env.OUTPUT_BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{matrix.buildConfiguration}} -A ${{matrix.buildPlatform}} -DSDL_STATIC=$SDL_STATIC -DSDL_SHARED=$SDL_SHARED -DSPDLOG_BUILD_SHARED=$SPDLOG_BUILD_SHARED -DBUILD_STATIC_LIBS=$BUILD_STATIC_LIBS -DSPDLOG_FMT_EXTERNAL=$SPDLOG_FMT_EXTERNAL -DSPDLOG_FMT_EXTERNAL_HO=$SPDLOG_FMT_EXTERNAL_HO
      env:
        SDL_STATIC: ON
        SDL_SHARED: OFF
        SPDLOG_BUILD_SHARED: OFF
        BUILD_STATIC_LIBS: ON
        SPDLOG_FMT_EXTERNAL: ON
        SPDLOG_FMT_EXTERNAL_HO: OFF
      shell: pwsh

    - name: Cmake Build
      # Build your program with the given configuration
      run: cmake --build ${{env.OUTPUT_BUILD_DIR}}
      shell: pwsh
