name: ZEngine Window Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  PROJECT_ROOT_DIR: .
  OUTPUT_BUILD_DIR: .\out\build

jobs:
  Windows-Build:
    runs-on: windows-2019
    strategy:
      matrix:
          buildSystem: [Windows]
          buildPlatform: [x64]
          buildConfiguration: [Debug, Release]

    steps:      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
        
    - name: Configure CMake
      run: cmake -S ${{env.PROJECT_ROOT_DIR}} -B ${{env.OUTPUT_BUILD_DIR}} -G "Visual Studio 16 2019" -A ${{matrix.buildPlatform}} -DCMAKE_SYSTEM_NAME=${{matrix.buildSystem}} -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSPDLOG_BUILD_SHARED=OFF -DBUILD_STATIC_LIBS=ON -DSPDLOG_FMT_EXTERNAL=ON -DSPDLOG_FMT_EXTERNAL_HO=OFF
      shell: pwsh

    - name: CMake Build
      run: cmake --build ${{env.OUTPUT_BUILD_DIR}} --config ${{matrix.buildConfiguration}}
      shell: pwsh
